import struct

UDP_PORT = 13122
MAGIC_COOKIE = 0xabcddcba
OFFER_TYPE = 0x2
REQUEST_TYPE = 0x3
PAYLOAD_TYPE = 0x4

OFFER_FORMAT = '!I B H 32s'
REQUEST_FORMAT = '!I B B 32s'
PAYLOAD_CLIENT_FORMAT = '!I B 5s'
PAYLOAD_SERVER_FORMAT = '!I B B H B'
